name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    - name: Run cargo-make
      uses: dtolnay/rust-toolchain@stable
    - uses: davidB/rust-cargo-make@v1.10.0
    - name: Run all
      run: cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
